
package at.ac.tuwien.big.we.highscore;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import at.ac.tuwien.big.we.highscore.data.HighScoreRequestType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublishHighScoreEndpoint", targetNamespace = "http://big.tuwien.ac.at/we/highscore")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    at.ac.tuwien.dbai.ssd.ObjectFactory.class,
    at.ac.tuwien.big.we.highscore.ObjectFactory.class,
    at.ac.tuwien.big.we.highscore.data.ObjectFactory.class
})
public interface PublishHighScoreEndpoint {


    /**
     * 
     * 				Diese Operation dient zum Speichern eines WE Mensch Ärgere Dich Nicht Ergebnisses 
     * 				am WE Highscore Board
     * 			
     * 
     * @param in
     * @return
     *     returns java.lang.String
     * @throws Failure
     */
    @WebMethod(operationName = "PublishHighScore", action = "/PublishHighScore")
    @WebResult(name = "HighScoreResponse", targetNamespace = "http://big.tuwien.ac.at/we/highscore/data", partName = "out")
    public String publishHighScore(
        @WebParam(name = "HighScoreRequest", targetNamespace = "http://big.tuwien.ac.at/we/highscore/data", partName = "in")
        HighScoreRequestType in)
        throws Failure
    ;

}
